### ISSUE TITLE
What does feature_maps parameter mean and how can I change it to more layers than 1 besides last layer

### ISSUE THREAD

**Issue by BrunoQin** [kekeblom/DeepCGP#1]
Hi, I read the paper and your code, I think is an excellent and helpful work for me! I have a small question here. In the parameter settings there is a parameter named `feature_maps` and in `model.py`, there is an assertion:
`assert len(feature_maps) == (len(Ms) - 1)`
the default `feature_maps` is 10, is this the height and weight of conv_gp layer?
Because there is only 1 `feature_maps` in setting, so is there one layer in conv_gp? and how to transfer it more than 1 layer?

**Comment by kekeblom** [comment]
Glad you like it!

The `feature-maps` parameter corresponds to the `C_i` parameter in the paper which correspond to the amount of independent (but with shared Z) GPs at each layer. They are given as a comma separated list. For example, by running `python mnist.py --feature-maps 10 -M 128,256` will define a two layer model with 10 GPs in the first layer, 128 inducing points in the first layer and 256 inducing points in the second layer. 

There is one less of the `feature-maps` arguments than the `M` arguments because the last layer will always one latent GP for each class in the classification problem.

Let me know if this clears things up.

**Comment by BrunoQin** [comment]
Appreciated your reply so quickly！!

I re-read the paper again and find the parameter, I want to share you what I have understand with your paper: the traditional convolution function is use a convolution kernel or some convolution kernels (filters). The number of this is actually the parameter `feature_maps`, and in your paper, you have used GP to replace convolution function, and the number of GP for each layer is the parameter `feature_maps` which determined the number of next layer. These GPs are independent and shared prior, they can generate one pixel for next layer.

So, If I got the point, may I have another question, I want to change this code to a regression question, and how can I change the loss function to RMSE. Could you give some advice?

Thank you again for your nice answer!

**Comment by kekeblom** [comment]
To do regression, you just change the likelihood to Gaussian or whatever type of regression you want to do. If you only have one regression output the `num_outputs` parameter of the last layer is set to one.

**Comment by BrunoQin** [comment]
Thank you! I will have a try! I'll tell you the result afterwards.

**Comment by BrunoQin** [comment]
Hi, It's so nice of you! 
Today I try to modify the model to a regression model with the parameter you have mentioned, and add my own dataset. `SVGP_layer` occurs the following question:
`TypeError: __init__() missing 1 required positional argument: 'Z'`
in `model.py` 192 line. I have set up the submodule but it happened. I don't know why, I have tried to fix it in adding argument 'Z', but it occurs another question about no argument `feature` or no argument `q_mu` when I delete `feature`. I want to know what version of submodule you used or some way to fix it.

Thank you!

**Comment by kekeblom** [comment]
Hi,

It seems the submodule was pointing to a revision which was not on the github repo. I just pushed a fix. 

Let me know if this fixes the issue.

Cheers,
Ken

**Comment by BrunoQin** [comment]
Some strange problem occurs:
`tensorflow.python.framework.errors_impl.InvalidArgumentError: Operation 'DGP/ExtractImagePatches_1' has no attr named '_XlaCompile'.`

`ValueError: Tensor conversion requested dtype float32 for Tensor with dtype float64: 'Tensor("gradients/DGP/ExtractImagePatches_1_grad/Reshape_1:0", shape=(?, ?), dtype=float64)'`

`TypeError: Input 'b' of 'SparseTensorDenseMatMul' Op has type float64 that does not match type float32 of argument 'a_values'.`
The third exception occurs in `Experiment.py` `AdamOptimizer`

**Comment by kekeblom** [comment]
That's a bug in tensorflow which I fixed. The fix was included in version 1.11.0 of tensorflow. You will have to use tensorflow version 1.11.0 or above.

**Comment by BrunoQin** [comment]
I have tried `tensorflow` 1.11.0, 1.2.0, 1.3.0 with `gpflow` 1.2.0, 1.3.0. but still have an exception:
`Object was never used (type <class 'tensorflow.python.framework.ops.Tensor'>):`
It's very confused which version I should use

**Comment by kekeblom** [comment]
The latest version of gpflow should be fine. I can't say much about that error.

Can you post a minimal example script where the exception is thrown?

**Comment by BrunoQin** [comment]
I wil try the latest gpflow, If that doesn't work, I will post a script.

**Comment by BrunoQin** [comment]
I forked the latest GPflow and install it with tensorflow 1.6.0. It seems work, but there still a little problem occuring in `mean_function.py` 17 lines when I run the mnist experiment:
`TypeError: Value passed to parameter 'input' has DataType float64 not in list of allowed values: float16, bfloat16, float32`
It seems `tf.nn.conv2d` input is not a correct type.
My own dataset loading is as following:
```
def load_ocean():
    # read data
    with gzip.open('OCEAN_data/redata.pkl.gz') as fp:
        redata = np.array(pickle.load(fp)).astype(np.float32)

    with gzip.open('OCEAN_data/nino.pkl.gz') as fp:
        nino = np.array(pickle.load(fp)).astype(np.float32)

    redata = np.array(redata).astype(np.float32)
    nino = np.array(nino).astype(np.float32)
    X = redata[0:4600]
    Y = nino[11:4611]
    Xt = redata[4601:4789]
    Yt = nino[4612:4800]
    return X, Y, Xt, Yt
```
I just use a small dataset for a test. the picture is `150x160x1` and `redata` is formed as MNIST `X`.

**Comment by kekeblom** [comment]
Are you able to run the `python conv_gp/mnist.py` example?

Maybe the `float_type` of gpflow is set to `float64` and you are feeding in `float32`?

**Comment by BrunoQin** [comment]
Finally, I use GTX1080 to train the `mnist.py` model with`tensorflow-gpu` 1.11.0 and `gpflow` 1.3.0. It seems it started to train, but there is no log output in console, I don't know whether it's correct. the `results `dictionary have generated two files but the `log.csv` is empty.

**Comment by kekeblom** [comment]
Right. That means it's working. The `test-every` parameter will set the logging frequency.

Try loading your dataset using the same floating point accuracy as you have gpflow configured. The default configuration defined in `gpflowrc` is float64.

**Comment by BrunoQin** [comment]
Hi! Thank you!  I almost run the model on my own dataset! And there is still a question: in `arguments.py`, what is the meaning of `--num-samples`?

By the way, when I trained my own model, `tensorboard.py` 99 lines will occur error, the meaning is `cannot reshape 7280 to [4, 13, 13, 10]`. So in `experiment.py` 34 lines I add a comment symbol to not run this line. Will this effect the results? or why this error?
